### PR TITLE
take function definition out of the loop

### PR DESCRIPTION
**Pull request by rmanzoni**

### CODE REVIEW

**Comment by rmanzoni** [comment]
This change does indeed fix the batch processing, but for some reasons, it also messes up the weight calculation...

Investigating...

schermata 2016-04-03 alle 21 34 16
schermata 2016-04-03 alle 21 33 51

**Comment by rmanzoni** [comment]
mmm... not really, this is not the reason.
I will continue tomorrow

**Comment by steggema** [comment]
I think I factored out the cross section, but not N(gen events) since it's needed to know the weights at production time. This means you'll have to multiply by cross section (as usual) and manually set N(gen events) = 1 in the inputs to the plotting script (not changed yet since not done yet).

An alternative scheme would be to ignore the weights and set up all sub-components as individual DY contributions based on generator cuts, but as of now it would make the plotting quite slow (though it's conceptually nice and can handle non-100% productions, let's maybe move to this once we have a faster plotting implemented)

**Comment by rmanzoni** [comment]
I am quite sure that one thing is missing though
https://github.com/steggema/cmgtools-lite/blob/HTTUnscheduled/H2TauTau/python/proto/analyzers/NJetsAnalyzer.py#L131
the njet weight is not included in the event weight.
Is this intentional (basically at the plotting level one can require 'weight_njet \* weight' as total weight, but that would be a bit counterintuitive)?

**Comment by steggema** [comment]
Ok this we can fix to make it inline with https://github.com/steggema/cmgtools-lite/blob/HTTUnscheduled/H2TauTau/python/proto/analyzers/NJetsAnalyzer.py#L121

**Pull request merged**
